{
 "title": "Istio Galley Dashboard",
 "description": "Galley-specific dashboard for Istio 1.0",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Validation Webhook Certificate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "galley_validation_cert_key_updates{job=\"galley\"}",
     "legendFormat": "Key Updates"
    },
    {
     "expr": "galley_validation_cert_key_update_errors{job=\"galley\"}",
     "legendFormat": "Key Update Errors: {{ error }}"
    }
   ]
  },
  {
   "title": "Resource Validation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_passed{job=\"galley\"}) by (group, version, resource)",
     "legendFormat": "Passed: {{ group }}/{{ version }}/{{resource}}"
    },
    {
     "expr": "sum(galley_validation_failed{job=\"galley\"}) by (group, version, resource, reason)",
     "legendFormat": "Failed: {{ group }}/{{ version }}/{{resource}} ({{ reason}})"
    }
   ]
  },
  {
   "title": "Validation HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(galley_validation_http_error{job=\"galley\"}) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  }
 ]
}