{
 "title": "Microservices (Summary)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jvm_memory_used_bytes, namespace)"
   },
   {
    "name": "application",
    "label": "Application",
    "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\"}, application)"
   }
  ]
 },
 "panels": [
  { "title": "Pod Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ERROR Logging ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(logback_events_total{level=\"error\", application=\"$application\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "JVM Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total Heap ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (jvm_memory_used_bytes{application=\"$application\", namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "{{pod}}  - used"
    },
    {
     "expr": "sum by(pod) (jvm_memory_max_bytes{application=\"$application\", namespace=\"$namespace\", area=\"heap\"})",
     "legendFormat": "{{pod}} - max"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "repeat": "pod",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{application=\"$application\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Incoming / Outgoing Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(source_app) (irate(istio_requests_total{destination_service_name=~\"$namespace-refapp-$application\"}[5m]))",
     "legendFormat": "{{source_app}}"
    }
   ]
  },
  {
   "title": "Outgoing Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(destination_service_name) (irate(istio_requests_total{source_app = \"$namespace-refapp-$application\"}[5m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  }
 ]
}