<?php
# https://sourcegraph.com/github.com/salesagility/SuiteCRM@v7.11.10/-/blob/install/install_utils.php#L1627
$sugar_config_si  = array (
    'dbUSRData' => 'create',
    'default_currency_iso4217' => 'USD',
    'default_currency_name' => 'US Dollar',
    'default_currency_significant_digits' => '2',
    'default_currency_symbol' => '$',
    'default_date_format' => 'd-m-Y',
    'default_decimal_seperator' => '.',
    'default_export_charset' => 'ISO-8859-1',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator' => ',',
    'default_time_format' => 'H:i',
    'export_delimiter' => ',',
    'setup_db_admin_password' => getenv('DB_PASSWORD'),
    'setup_db_admin_user_name' => getenv('DB_USER'),
    'setup_db_create_database' => 1,
    'setup_db_database_name' => getenv('DB_NAME'),
    'setup_db_drop_tables' => 0,
    'setup_db_host_name' => getenv('DB_HOST'),
    'setup_db_pop_demo_data' => false,
    'setup_db_type' => getenv('DB_TYPE'),
    'setup_db_username_is_privileged' => true,
    'setup_site_admin_password' => getenv('ADMIN_PASSWORD'),
    'setup_site_admin_user_name' => getenv('ADMIN_NAME'),
    'setup_site_url' => getenv('SITE_URL'),
    'setup_system_name' => getenv('SITE_NAME')
);
